version: "3.2"
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: broccoli
      POSTGRES_USER: broccoli
      POSTGRES_PASSWORD: broccoli
    ports:
      - "5432:5432"
    volumes:
    - "pg_data:/var/lib/postgresql/data"
  api:
    build: .
    environment:
      DATASOURCE_URL: jdbc:postgresql://db:5432/broccoli
      DATASOURCE_USERNAME: broccoli
      DATASOURCE_PASSWORD: broccoli
    depends_on:
      - db
    ports:
    - 8080:8080
volumes:
  pg_data: